---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6InJaVHNpcnY5VmZfRWh6QlZHYU1KRThtVXM0TnB0bXFod2lXek5sVFJ0V2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4ZWM2MDE2Zi0xYjhhLTQ2NTAtYTkxNi1jZGZjNTZlZTE5NDEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.AJwV_R9YuEpWr8GczuW-FrQkvZV4y3nuKpj3Id0tR6Ah4JwB-XdMLDvK6GtdbUtb23jI2iGHqIvaF1Eb1vTDLTGggoTdTJTYxCWXmsRisGEZLthfeeViSfTJd8KW6KYrfGc_RsOLpX8H2s3qkeJ6ZC3AJNsxQP6IE58Uk7ttfb6VxkebASA4XaCLDyU646Y3ttm4r5CiB1KzsqnA2MHJ6xkFpSr2SCiE6oUvI-IBkpqRuwk5hblAptyeioGEkwsODN438LZpQgr8pzoG_EbR-ouV0196HVpQ4rA7FeweIfCFNtCRzM1PXDKYNw5soC6S8ivFzt_vZSezTN6L2LI4dYjSKXemz9yfiTNUJXtl5DTWt7vwVXDHJb7AxeJtgTRnaXPTZmnSjC2NDfGb-_T0Yo6irr4dHa3PI5J-qO4uCZSkqx3XpkDcF2U32p8M4Y2cBdYWzok5twS56uFYAtLdOKJ9hT6MdYJ8wVtRrdbMC4stxoaiofcUbq1r_Ri2Uv6aIRmkOEOqET4hmg-NWeNNETUU9jfwmnOeGGEJwlXzVAHRyceR_afSic1DhurkNT8f6nlyJvtyR2ySP0ObrS7uOUzSYPEB1bWB02cx8ELvBgHB-FKRVNFC8AFHsv5KJgNhjm2JMOCEHSggfiCtPwxekl2QONPRQNnQCVde6Ajy-X4
  GITHUB_TOKEN: <placeholder for github token>
